In [1]:
import pandas as pd

In [2]:
messi = pd.read_csv("eventsMessi.csv")

C:\Users\yashaswi\AppData\Local\Temp\ipykernel_2428\415572335.py:1: DtypeWarning: Columns (1,4,5,6,7,10,12,13,14,16,17,18,19,28,40,42,44,46,49,50,64,65,66,67,68,69,70,71,73,74,75,76,83,84,85,86,88,89,90,91,92,93,97,98,99,100,101,102,103,104,105,106,107,113) have mixed types. Specify dtype option on import or set low_memory=False.
  messi = pd.read_csv("eventsMessi.csv")

In [3]:
goals = messi[messi['shot_outcome']=='Goal']

In [4]:
goals

,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,...,player_off_permanent,goalkeeper_success_out,half_end_early_video_end,goalkeeper_saved_to_post,x_start,y_start,x_end,y_end,x_carry_end,y_carry_end
8755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,103.9,37.9,NaN,NaN,NaN,NaN
8756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.8,43.8,NaN,NaN,NaN,NaN
8760,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,112.3,45.1,NaN,NaN,NaN,NaN
8765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,102.5,52.6,NaN,NaN,NaN,NaN
8789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,107.1,30.2,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,104.9,44.7,NaN,NaN,NaN,NaN
114702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,107.5,35.4,NaN,NaN,NaN,NaN
114703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,109.8,27.1,NaN,NaN,NaN,NaN
114716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,116.2,32.8,NaN,NaN,NaN,NaN
115183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,106.0,29.3,NaN,NaN,NaN,NaN

In [23]:
goalMID = goals['match_id'].tolist()

In [6]:
mMatches = pd.read_csv("messiMatches.csv")

In [59]:
goalDate = pd.DataFrame(columns=['goalNumber', 'Date'])
i=len(goalMID)
for mid in goalMID:
    for index,row in mMatches.iterrows():
        if(row['match_id'] == mid):
            goalDate.loc[len(goalDate)] = [i,row['match_date']]
            i=i-1

In [60]:
goalDate

     goalNumber        Date
0           474  2021-01-09
1           473  2021-01-09
2           472  2021-05-16
3           471  2021-02-07
4           470  2020-12-13
..          ...         ...
469           5  2005-11-27
470           4  2006-01-29
471           3  2006-01-29
472           2  2006-01-15
473           1  2005-05-01

[474 rows x 2 columns]

In [55]:
assistMID = messi[messi['pass_goal_assist']==True]['match_id'].tolist()

In [56]:
assistMID

[3773665,
 3773665,
 3773552,
 3773369,
 3773661,
 3773597,
 3773571,
 3773526,
 3773625,
 3773477,
 303516,
 303516,
 303430,
 303725,
 303725,
 303664,
 303682,
 303682,
 303680,
 303600,
 303600,
 303548,
 303548,
 303700,
 303707,
 303707,
 303707,
 303715,
 303377,
 15998,
 16029,
 16073,
 16086,
 16190,
 16265,
 16079,
 15973,
 15973,
 16205,
 16095,
 16095,
 16010,
 9799,
 9636,
 9736,
 9742,
 9765,
 9783,
 9695,
 9650,
 9811,
 9602,
 9726,
 9754,
 266989,
 267212,
 267670,
 266516,
 267373,
 267077,
 266299,
 266299,
 265952,
 266498,
 266498,
 266498,
 266986,
 266986,
 266310,
 266310,
 265944,
 265958,
 267274,
 266961,
 266160,
 266467,
 266490,
 266254,
 267183,
 265963,
 266117,
 266117,
 266916,
 70273,
 70273,
 265896,
 265866,
 266794,
 266794,
 266525,
 266741,
 266871,
 266871,
 266770,
 266770,
 70302,
 70291,
 267520,
 267675,
 266074,
 265918,
 70277,
 266256,
 266613,
 265857,
 267192,
 70304,
 70297,
 70256,
 70275,
 70275,
 70286,
 70309,
 70307,
 266827,
 266827,
 70219,
 69316,
 70225,
 70223,
 70223,
 69333,
 69343,
 69343,
 69334,
 69268,
 69314,
 70220,
 70220,
 70224,
 70224,
 69323,
 69307,
 69305,
 69278,
 69275,
 69275,
 69295,
 69270,
 69303,
 69269,
 69246,
 69280,
 69280,
 69299,
 69299,
 69289,
 69306,
 69306,
 69248,
 69253,
 69219,
 69242,
 69210,
 69255,
 69240,
 69233,
 69267,
 69254,
 69292,
 69232,
 69232,
 69231,
 69231,
 69189,
 69249,
 69138,
 69207,
 69207,
 69279,
 69230,
 69151,
 68360,
 68360,
 69186,
 69186,
 68364,
 68356,
 69146,
 68361,
 69141,
 69145,
 69145,
 68336,
 68326,
 68322]

In [61]:
assistDate = pd.DataFrame(columns=['assistNumber', 'Date'])
i=len(assistMID)
for mid in assistMID:
    for index,row in mMatches.iterrows():
        if(row['match_id'] == mid):
            assistDate.loc[len(assistDate)] = [i,row['match_date']]
            i=i-1

In [62]:
assistDate

     assistNumber        Date
0             186  2021-03-06
1             185  2021-03-06
2             184  2021-01-03
3             183  2021-03-15
4             182  2021-04-22
..            ...         ...
181             5  2007-12-15
182             4  2007-12-15
183             3  2007-06-17
184             2  2006-08-28
185             1  2005-12-17

[186 rows x 2 columns]